Map<String, String> arLocale = {
  // intro ***
  'boarding1_title': 'تصفح جميع الأصناف',
  'boarding2_title': 'عروض وخصومات رائعة',
  'boarding3_title': 'التوصيل خلال 30 دقيقة',
  'boarding1_info':
      'مكان واحد يجمع جميع المنتجات بمختلف الأصناف التي تحتاجها الأسرة',
  'boarding2_info': 'عروض دائمة على أفضل المنتجات وخصومات لزبائننا باستمرار',
  'boarding3_info': 'سوف تتلقى طلبك بسرعة وسهولة على عنوانك المحدد',
  'login_greeting': 'أهلاً بك في متجرنا',
  'to_login': 'تابع برقم الهاتف',
  'to_register': 'أنشئ حساب جديد',
  // auth
  'phone_number': 'رقم الجوال',
  'password': 'كلمة المرور',
  'required_error_message': '* هذا الحقل اجباري',
  'phone_length_error_message': '!رقم الجوال يجب ان يكون 9 أرقام',
  'password_length_error_message': '!كلمة المرور يجب ان تكون 8 رموز على الأقل',
  'login': 'تسجيل الدخول',
  'sign_up': 'إنشاء حساب',
  'reset_success': 'لقد أعدت ضبط كلمة المرور بنجاح',
  'verified': 'تم التأكيد',
  'verified_success': 'مرحى!! تم تأكيد رقم هاتفك بنجاح',
  'create_password': 'إنشاء كلمة مرور جديدة',
  'login_now': 'تسجيل الدخول بكلمة المرور الجديدة',
  // login
  'forget_password': 'نسيت كلمة المرور؟',
  'have_no_account': '  ألا تملك حسابا؟',
  'welcome': 'أهلاً وسهلاً',
  // register
  'register_greeting': 'أهلاً بك في تطبيقنا\nالبقالة الاكترونية',
  'name': 'الإسم',
  'gender': 'الجنس',
  'male': 'ذكر',
  'female': 'أنثى',
  'city': 'المدينة',
  'already_have_account': '  ألديك حساب بالفعل؟',
  // verification
  'verification_message': 'تم إرسال كود تفعيل لرقم هاتفك',
  'enter_code': 'أدخل كود التفيعل',
  'get_no_code': 'ألم تحصل على كود تفعيل؟',
  'resend': 'إعادة الإرسال',
  'resent_message': 'تم إرسال كود تفعيل جديد => ',
  'verify': 'أكد',
  'code_not_correct': 'كود التفعيل المدخل غير صحيح !!',
  // reset password
  'new_password': 'كلمة مرور جديدة',
  'add_new_password': 'أضف كلمة مرور جديدة',
  'confirm_password': 'أعد كلمة المرور',
  'done': 'تمت',
  'passwords_not_match': 'كلمات المرور غير متطابقة',
  // forget password
  'reset_password': 'إعادة ضبط كلمة المرور',
  'forget_opening_sentence':
      'رجاءً أدخل رقم هاتفك. سوف نرسل كود لهاتفك لإعادة ضبط كلمة المرور',
  'send_code': 'أرسل كود التفعيل',
  'code_sent': 'تم إرسال كود التفعيل =>',
  // Change Password
  'change_password': 'غير كلمة السر',
  'old_password': 'كلمة السر القديمة',
  // Home Screen ***
  'categories': 'الأصناف',
  'favorite_list': 'قائمة المفضلة',
  'profile': 'الملف الشخصي',
  'invite_friend': 'شارك التطبيق',
  'share': 'شارك التطبيق',
  'facebook': 'فيسبوك',
  'whatsup': 'واتس أب',
  'telegram': 'تيليجرام',
  'twitter': 'تويتر',
  'linkedin': 'لينكد إن',
  'message': 'رسالة',
  'about': 'عن التطبيق',
  'faqs': 'الأسئلة الأكثر تكراراً',
  'help_center': 'مركز المساعدة',
  'contact': 'اتصل بنا',
  'terms_conditions': 'البنود والشروط',
  'policy_privacy': 'سياسة الخصوصية',
  'rate_app': 'قيم تطبيقنا',
  'home': 'الرئيسية',
  'favorite': 'المفضلة',
  // Home
  'category': 'الأصناف',
  'latest_products': 'آخر المنتجات',
  'popular_products': 'منتجات مشهورة',
  'view_all': 'اعرض الكل',
  // Categories
  'choose_category': 'إختر الصنف',
  // favorites
  'no_favorites': 'لا يوجد منتجات مضافة في المفضلة',
  'add_cart': 'أضف إلى السلة',
  'add_success': 'تمت الإضافة إلى السلة بنجاح',
  'undo': 'تراجع',
  'cancelling': 'إلغاء الأمر',
  'remove_cart': 'يتم الآن الإزالة من السلة',
  'already_added': 'تم الإضافة مسبقاً',
  'add_fail': 'هذا المنتج ينتظر بالسلة بالفعل',
  'cart_updated': 'تحديث المنتج',
  'updated_succes': 'تم تحديث كمية المنتج المحددة بنجاح',
  // profile
  'my_profile': 'ملفي الشخصي',
  'notifications': 'الإشعارات',
  'settings': 'الإعدادات',
  'payment': 'الدفع',
  'log_out': 'تسجيل الخروج',
  'all_orders': 'جميع\nطلباتي',
  'offers_promos': 'العروض و\nالتخفيضات',
  'offers_promos_title': 'العروض والتخفيضات',
  'no_offers': 'لا عروض حتى الآن !!',
  'delivery_address': 'عنوان\nالتوصيل',
  // profile options
  'select_city': 'اختر المدينة',
  'birth_date': 'تاريخ الميلاد',
  'language': 'اللغة',
  'app_notifications': 'إشعارات التطبيق',
  'phone_notifications': 'إشعارات الهاتف',
  'offer_notifications': 'إشعارات العروض',
  'dark_mode': 'الوضع المظلم',
  'restore_dialog': 'استعادة الإعدادات الإفتراضية؟؟ ',
  'restore': 'استعادة الافتراضيات',
  // orders
  'order': 'طلب',
  'no_orders': 'للا طلبات حتى الآن',
  'no_orders_info': 'للأسف لم تطلب أي منتج بعد',
  'browse_products': 'تصفح المتجات',
  'fail_order': 'نأسف! فشل الطلب',
  'fail_order_info': 'نأسف! حدث خطاُ ما، الرجاء المحاولة مجدداً',
  'try_again': 'حاول مجدداً',
  'browse_home': 'انتقل للصفحة الرئيسية',
  'success_order': 'تم طلب المنتج بنجاح ',
  'success_order_info':
      'شكراً لط على الطلب. تم إضافة طلبك بنجاح. تابع الطلب من فضلك',
  'track_order': 'تتبع الطلب',
  'continue': 'استمر',
  // orders screen
  'my_orders': 'طلباتي',
  // drawer
  'common_quetions': 'الأسئلة الأكثر شيوعاً',
  'search': 'بحث',
  'help_center_opening': 'أهلا بك! كيف يمكنني مساعدتك؟',
  'top_questions': 'أكثر الأسئلة',
  'topics': 'المواضيع',
  // addresses
  'delivery_addresses': 'عناوين التوصيل',
  'address': 'عنوان',
  'building': 'البناية',
  'flat': 'رقم الشقة',
  'phone': 'الجوال',
  'edit': 'تحرير',
  'delete': 'حذف',
  'edit_address': 'تحرير العنوان',
  'add_address': 'أضف عنوان جديد',
  'address_name': 'اسم العنوان',
  'address_details': 'تفاصيل العنوان',
  'building_num': 'رقم/اسم البناية',
  'flat_num': 'رقم الشقة',
  'default_address': 'اجعله عنوان التسوق الافتراضي',
  'save_address': 'احفظ العنوان',
  // cart
  'cart': 'السلة',
  'total_count': 'العدد الكلي',
  'products': 'المنتجات',
  'total_weight': 'الوزن الاجمالي',
  'total_price': 'السعر الاجمالي',
  'checkout': 'الدفع',
  'select_address': 'اختر عنوان التوصيل',
  'add_new': 'أضف عنواناً',
  'select_payment': 'اختر نظام الدفع',
  'cash': 'نقداً عند التوصيل',
  'payment_card': 'بطاقة دفع الكتروني',
  'master_card': 'Master Card',
  'pay_now': 'ادفع الآن',
  'opps': 'أوبس!!',
  'empty_cart': 'نأسف! لا يوجد أي منتجات بالسلة',
  'start_browsing': 'استمر بالتصفح',
  // products
  'details': 'تفاصيل',
  'weight': 'الوزن:  ',
  'quantity': 'الكمية المتاحة:  ',
  'product_details': 'تفاصيل المنتج',
  'review': 'تقييم',
  'rate_product': 'قيم المنتج',
  'cancel': 'إلغاء',
  'ok': 'حسناً',
  'buy_now': 'اشترِ الآن',
  // coctail
  'no_data': 'لا يوجد بيانات',
  'unfound': 'الصفحة غير موجودة',
  'unfound_st1': 'أوبس!! خطأُ ما حصل',
  'unfound_st2': 'نأسف، حصل خطاُ ما\nرجاءً حاول مرة أخرى',
};
