Map<String, String> enLocale = {
  // intro ***
  'boarding1_title': 'Browse all the category',
  'boarding2_title': 'Amazing Discounts & Offers',
  'boarding3_title': 'Delivery in 30 Min',
  'boarding1_info':
      'One place that gathers all the products of various kinds that the family needs',
  'boarding2_info':
      'Permanent offers on the best products and discounts for our customers constantly',
  'boarding3_info':
      'You will receive your order quickly and easily at your specified address',
  'login_greeting': 'Welcome to our',
  'to_login': 'Continue with Phone',
  'to_register': 'Create an account',
  // auth ***
  'phone_number': 'Phone Number',
  'password': 'Password',
  'required_error_message': 'This field is required *',
  'phone_length_error_message': 'Phone number must be 9 digits!',
  'password_length_error_message': 'Password must be 8 characters at least!',
  'login': 'Login',
  'sign_up': 'Sign Up',
  'reset_success': 'You have successfully reset your password',
  'verified': 'Verified',
  'verified_success':
      'Hurrah!! You have successfully verified the Phone number.',
  'create_password': 'Create new password',
  'login_now': 'Login with new password',
  // login
  'forget_password': 'Forget Password?',
  'have_no_account': 'Don\'t have an account?  ',
  'welcome': 'Welcome',
  // register
  'register_greeting': 'Welcome to our\ngrocery app',
  'name': 'Name',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'city': 'City',
  'already_have_account': 'Already have an account?  ',
  // verification
  'verification_message': 'We have sent a verification code to your mobile',
  'enter_code': 'Enter the 4 digit code',
  'get_no_code': 'Didn\'t get code?  ',
  'resend': 'Resend',
  'resent_message': 'A new code has been sent => ',
  'verify': 'Verify',
  'code_not_correct': 'Verification Code is not correct!!',
  // reset password
  'new_password': 'New Password',
  'add_new_password': 'Add new password',
  'confirm_password': 'Confirm Password',
  'done': 'Done',
  'passwords_not_match': 'Passwords do not match',
  // forget password
  'reset_password': 'Reset your password',
  'forget_opening_sentence':
      'Please enter your number. We will send a code to your phone to reset your password.',
  'send_code': 'Send Me Code',
  'code_sent': 'Verification code is sent =>',
  // Change Password
  'change_password': 'Change Password',
  'old_password': 'Old Password',
  // Home Screen ***
  'categories': 'Categories',
  'favorite_list': 'My Favorite List',
  'profile': 'Profile',
  'invite_friend': 'Invite Friend',
  'share': 'Share App',
  'facebook': 'Facebook',
  'whatsup': 'Whatsup',
  'telegram': 'Telegram',
  'twitter': 'Twitter',
  'linkedin': 'Linkedin',
  'message': 'Message',
  'about': 'About Us',
  'faqs': 'FAQs',
  'help_center': 'Help Center',
  'contact': 'Contact Us',
  'terms_conditions': 'Terms & Conditions',
  'policy_privacy': 'Privacy Policy',
  'rate_app': 'Rate Our App',
  'home': 'Home',
  'favorite': 'Favorite',
  // Home
  'category': 'Category',
  'latest_products': 'Latest Products',
  'popular_products': 'Popular Products',
  'view_all': 'View All',
  // Categories
  'choose_category': 'Choose a Category',
  // favorites
  'no_favorites': 'No products marked as Favorite ',
  'add_cart': 'Add to Cart',
  'add_success': 'Added to cart successfully',
  'undo': 'UNDO',
  'cancelling': 'Cancelling',
  'remove_cart': 'Removing from Cart in progress',
  'already_added': 'Already Added',
  'add_fail': 'This product waiting in the cart indeed!',
  'cart_updated': 'Updated Scuccessfully',
  'updated_succes': 'Product quantity has been updated successfully',
  // profile
  'my_profile': 'My Profile',
  'notifications': 'Notifications',
  'settings': 'Settings',
  'payment': 'Payment',
  'log_out': 'Log out',
  'all_orders': 'My All\nOrders',
  'offers_promos': 'Offer &\nPromos',
  'offers_promos_title': 'Offer & Promos',
  'no_offers': 'No Offers Yet !!',
  'delivery_address': 'Delivery\nAddress',
  // profile options
  'select_city': 'Select City',
  'birth_date': 'Birth Date',
  'language': 'Language',
  'app_notifications': 'App Notifications',
  'phone_notifications': 'Phone Notifications',
  'offer_notifications': 'Offer Notifications',
  'dark_mode': 'Dark Mode',
  'restore_dialog': 'Restore default settings?',
  'restore': 'Restore Defaults',
  // orders
  'order': 'Order',
  'no_orders': 'No Orders Yet',
  'no_orders_info': 'Sorry you haven\'t placed any order yet.',
  'browse_products': 'Browse Products',
  'fail_order': 'Sorry, Order has Failed',
  'fail_order_info': 'Sorry, somethings went wrong. Please try again.',
  'try_again': 'Try Again',
  'browse_home': 'Browse Home',
  'success_order': 'Order Placed Successfully ',
  'success_order_info':
      'Thanks for your order. Your order has placed successfully. Please continue your order.',
  'track_order': 'Track Order',
  'continue': 'Continue',
  // orders screen
  'my_orders': 'My Orders',
  // drawer
  'common_quetions': 'Most Common Quetions',
  'search': 'Search',
  'help_center_opening': 'Hi! How can we help?',
  'top_questions': 'Top Questions',
  'topics': 'Topics',
  // addresses
  'delivery_addresses': 'Delivery Addresses',
  'address': 'Address',
  'building': 'Building',
  'flat': 'Flat no.',
  'phone': 'Phone',
  'edit': 'Edit',
  'delete': 'Delete',
  'edit_address': 'Edit Address',
  'add_address': 'Add New Address',
  'address_name': 'Address Name',
  'address_details': 'Address Details',
  'building_num': 'Building Name/Number',
  'flat_num': 'Flat Number',
  'default_address': 'Make Default Shipping address',
  'save_address': 'Save Address',
  // cart
  'cart': 'Cart',
  'total_count': 'Total Count',
  'products': 'Products',
  'total_weight': 'Total Weight',
  'total_price': 'Total Price',
  'checkout': 'Checkout',
  'select_address': 'Select delivery address',
  'add_new': 'Add New',
  'select_payment': 'Select payment system',
  'cash': 'Cash on delivery',
  'payment_card': 'Payment card',
  'master_card': 'Master Card',
  'pay_now': 'Pay Now',
  'opps': 'Opps!!',
  'empty_cart': 'Sorry, you have no product in your cart.',
  'start_browsing': 'Start Browsing',
  // products
  'details': 'Details',
  'weight': 'Weight:  ',
  'quantity': 'Available Quantity:  ',
  'product_details': 'Product Details',
  'review': 'Review',
  'rate_product': 'Rate Product',
  'cancel': 'Cancel',
  'ok': 'Ok',
  'buy_now': 'Buy Now',
  // coctail
  'no_data': 'No Data',
  'unfound': 'Unfound Page',
  'unfound_st1': 'oppss!! something wrong',
  'unfound_st2': 'Sorry, something went wrong\nplease try again.',
};
